openapi: 3.0.0
info:
  title: Djangolang
  version: "1.0"
paths:
  /logical-things:
    get:
      tags:
        - LogicalThing
      operationId: GetLogicalThings
      responses:
        "200":
          description: Successful List Fetch for LogicalThings
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  objects:
                    type: array
                    items:
                      $ref: "#/components/schemas/LogicalThing"
                  status:
                    type: integer
                    format: int32
                  success:
                    type: boolean
                required:
                  - status
                  - success
        default:
          description: Failed List Fetch for LogicalThings
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  status:
                    type: integer
                    format: int32
                  success:
                    type: boolean
                required:
                  - status
                  - success
    post:
      tags:
        - LogicalThing
      operationId: PostLogicalThings
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/LogicalThing"
        required: true
      responses:
        "200":
          description: Successful List Create for LogicalThings
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  objects:
                    type: array
                    items:
                      $ref: "#/components/schemas/LogicalThing"
                  status:
                    type: integer
                    format: int32
                  success:
                    type: boolean
                required:
                  - status
                  - success
        default:
          description: Failed List Create for LogicalThings
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  status:
                    type: integer
                    format: int32
                  success:
                    type: boolean
                required:
                  - status
                  - success
  /logical-things/{primaryKey}:
    get:
      tags:
        - LogicalThing
      operationId: GetLogicalThing
      parameters:
        - name: primaryKey
          in: path
          required: true
          schema: {}
      responses:
        "200":
          description: Successful Item Fetch for LogicalThings
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  objects:
                    type: array
                    items:
                      $ref: "#/components/schemas/LogicalThing"
                  status:
                    type: integer
                    format: int32
                  success:
                    type: boolean
                required:
                  - status
                  - success
        default:
          description: Failed Item Fetch for LogicalThings
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  status:
                    type: integer
                    format: int32
                  success:
                    type: boolean
                required:
                  - status
                  - success
    put:
      tags:
        - LogicalThing
      operationId: PutLogicalThing
      parameters:
        - name: primaryKey
          in: path
          required: true
          schema: {}
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LogicalThing"
        required: true
      responses:
        "200":
          description: Successful Item Replace for LogicalThings
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  objects:
                    type: array
                    items:
                      $ref: "#/components/schemas/LogicalThing"
                  status:
                    type: integer
                    format: int32
                  success:
                    type: boolean
                required:
                  - status
                  - success
        default:
          description: Failed Item Replace for LogicalThings
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  status:
                    type: integer
                    format: int32
                  success:
                    type: boolean
                required:
                  - status
                  - success
    patch:
      tags:
        - LogicalThing
      operationId: PatchLogicalThing
      parameters:
        - name: primaryKey
          in: path
          required: true
          schema: {}
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LogicalThing"
        required: true
      responses:
        "200":
          description: Successful Item Update for LogicalThings
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  objects:
                    type: array
                    items:
                      $ref: "#/components/schemas/LogicalThing"
                  status:
                    type: integer
                    format: int32
                  success:
                    type: boolean
                required:
                  - status
                  - success
        default:
          description: Failed Item Update for LogicalThings
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  status:
                    type: integer
                    format: int32
                  success:
                    type: boolean
                required:
                  - status
                  - success
    delete:
      tags:
        - LogicalThing
      operationId: DeleteLogicalThing
      parameters:
        - name: primaryKey
          in: path
          required: true
          schema: {}
      responses:
        "204":
          description: Successful Item Delete for LogicalThings
        default:
          description: Failed Item Delete for LogicalThings
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  status:
                    type: integer
                    format: int32
                  success:
                    type: boolean
                required:
                  - status
                  - success
  /physical-things:
    get:
      tags:
        - PhysicalThing
      operationId: GetPhysicalThings
      responses:
        "200":
          description: Successful List Fetch for PhysicalThings
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  objects:
                    type: array
                    items:
                      $ref: "#/components/schemas/PhysicalThing"
                  status:
                    type: integer
                    format: int32
                  success:
                    type: boolean
                required:
                  - status
                  - success
        default:
          description: Failed List Fetch for PhysicalThings
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  status:
                    type: integer
                    format: int32
                  success:
                    type: boolean
                required:
                  - status
                  - success
    post:
      tags:
        - PhysicalThing
      operationId: PostPhysicalThings
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/PhysicalThing"
        required: true
      responses:
        "200":
          description: Successful List Create for PhysicalThings
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  objects:
                    type: array
                    items:
                      $ref: "#/components/schemas/PhysicalThing"
                  status:
                    type: integer
                    format: int32
                  success:
                    type: boolean
                required:
                  - status
                  - success
        default:
          description: Failed List Create for PhysicalThings
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  status:
                    type: integer
                    format: int32
                  success:
                    type: boolean
                required:
                  - status
                  - success
  /physical-things/{primaryKey}:
    get:
      tags:
        - PhysicalThing
      operationId: GetPhysicalThing
      parameters:
        - name: primaryKey
          in: path
          required: true
          schema: {}
      responses:
        "200":
          description: Successful Item Fetch for PhysicalThings
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  objects:
                    type: array
                    items:
                      $ref: "#/components/schemas/PhysicalThing"
                  status:
                    type: integer
                    format: int32
                  success:
                    type: boolean
                required:
                  - status
                  - success
        default:
          description: Failed Item Fetch for PhysicalThings
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  status:
                    type: integer
                    format: int32
                  success:
                    type: boolean
                required:
                  - status
                  - success
    put:
      tags:
        - PhysicalThing
      operationId: PutPhysicalThing
      parameters:
        - name: primaryKey
          in: path
          required: true
          schema: {}
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PhysicalThing"
        required: true
      responses:
        "200":
          description: Successful Item Replace for PhysicalThings
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  objects:
                    type: array
                    items:
                      $ref: "#/components/schemas/PhysicalThing"
                  status:
                    type: integer
                    format: int32
                  success:
                    type: boolean
                required:
                  - status
                  - success
        default:
          description: Failed Item Replace for PhysicalThings
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  status:
                    type: integer
                    format: int32
                  success:
                    type: boolean
                required:
                  - status
                  - success
    patch:
      tags:
        - PhysicalThing
      operationId: PatchPhysicalThing
      parameters:
        - name: primaryKey
          in: path
          required: true
          schema: {}
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PhysicalThing"
        required: true
      responses:
        "200":
          description: Successful Item Update for PhysicalThings
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  objects:
                    type: array
                    items:
                      $ref: "#/components/schemas/PhysicalThing"
                  status:
                    type: integer
                    format: int32
                  success:
                    type: boolean
                required:
                  - status
                  - success
        default:
          description: Failed Item Update for PhysicalThings
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  status:
                    type: integer
                    format: int32
                  success:
                    type: boolean
                required:
                  - status
                  - success
    delete:
      tags:
        - PhysicalThing
      operationId: DeletePhysicalThing
      parameters:
        - name: primaryKey
          in: path
          required: true
          schema: {}
      responses:
        "204":
          description: Successful Item Delete for PhysicalThings
        default:
          description: Failed Item Delete for PhysicalThings
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  status:
                    type: integer
                    format: int32
                  success:
                    type: boolean
                required:
                  - status
                  - success
components:
  schemas:
    Any:
      type: object
      nullable: true
    LogicalThing:
      type: object
      properties:
        CreatedAt:
          type: string
          format: date-time
        DeletedAt:
          type: string
          format: date-time
          nullable: true
        ExternalID:
          type: string
          nullable: true
        ID:
          type: string
          format: uuid
        Metadata:
          type: object
          additionalProperties:
            type: string
            nullable: true
        Name:
          type: string
        ParentLogicalThingID:
          type: string
          format: uuid
          nullable: true
        ParentLogicalThingIDObject:
          $ref: "#/components/schemas/NullableLogicalThing"
        ParentPhysicalThingID:
          type: string
          format: uuid
          nullable: true
        ParentPhysicalThingIDObject:
          $ref: "#/components/schemas/NullablePhysicalThing"
        RawData:
          type: object
          nullable: true
        Tags:
          type: array
          items:
            type: string
        Type:
          type: string
        UpdatedAt:
          type: string
          format: date-time
    MapOfStringString:
      type: object
      additionalProperties:
        type: string
        nullable: true
    NullableAny:
      type: object
      nullable: true
    NullableLogicalThing:
      $ref: "#/components/schemas/LogicalThing"
    NullablePhysicalThing:
      $ref: "#/components/schemas/PhysicalThing"
    PhysicalThing:
      type: object
      properties:
        CreatedAt:
          type: string
          format: date-time
        DeletedAt:
          type: string
          format: date-time
          nullable: true
        ExternalID:
          type: string
          nullable: true
        ID:
          type: string
          format: uuid
        Metadata:
          type: object
          additionalProperties:
            type: string
            nullable: true
        Name:
          type: string
        RawData:
          type: object
          nullable: true
        Tags:
          type: array
          items:
            type: string
        Type:
          type: string
        UpdatedAt:
          type: string
          format: date-time
  responses: {}
