services:
    postgres:
        image: postgis/postgis:14-3.4
        platform: linux/amd64
        restart: always
        stop_grace_period: 0s
        healthcheck:
            interval: 5s
            timeout: 4s
            start_period: 10s
            test: ["CMD", "pg_isready", "-h", "localhost", "-U", "postgres"]
        environment:
            - POSTGRES_DB=some_db
            - POSTGRES_PASSWORD=some-password
        ports:
            - 5432:5432/tcp

    migrate:
        depends_on:
            postgres:
                condition: service_healthy
        image: migrate/migrate:v4.17.1
        restart: no
        stop_grace_period: 0s
        volumes:
            - ./database/migrations:/migrations
        command: >
            --source file:///migrations
            --database postgres://postgres:some-password@postgres:5432/some_db?sslmode=disable
            up

    post-migrate:
        depends_on:
            migrate:
                condition: service_completed_successfully
        image: postgis/postgis:14-3.4
        platform: linux/amd64
        restart: no
        stop_grace_period: 0s
        entrypoint: ["/bin/bash", "-c"]
        command: "PAGER=cat PGPASSWORD=some-password psql -h postgres -p 5432 -U postgres -a some_db -c 'VACUUM FULL; VACUUM ANALYZE;'"
